version: '3.7'
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password123
  graphql:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://postgres:password123@db/mealplanner?sslmode=disable
    depends_on:
      - db
    links:
      - db

volumes:
  pgdata:
